import { faker } from "@faker-js/faker";

const generateDiscounts = () => {
  return [
    {
      discount_name: "Seamless uniform product",
      discount_code: "MJM281",
      discount_status: "draft",
      discount_applies_to: "all",
      discount_value: 13,
      discount_type: "percentage",  
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 200,
      discount_uses_count: 141,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 5,
      discount_min_order_value: 50,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Phased grid-enabled pricing structure",
      discount_code: "YID346",
      discount_status: "draft",
      discount_applies_to: "specific",
      discount_value: 27,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 150,
      discount_uses_count: 129,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 3,
      discount_min_order_value: 30,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: ["Splashify 2.0"],
    },
    {
      discount_name: "Customer-focused tertiary parallelism",
      discount_code: "CFL369",
      discount_status: "expired",
      discount_applies_to: "specific",
      discount_value: 6,    
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.recent(),
      discount_max_use: 200,
      discount_uses_count: 196,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 1,
      discount_min_order_value: 15,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: false,
      discount_product_ids: ["Mastering the Grid"],
    },
    {
      discount_name: "Progressive incremental secured line",
      discount_code: "YTX201",
      discount_status: "active",
      discount_applies_to: "specific",
      discount_value: 21,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 120,
      discount_uses_count: 101,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 4,
      discount_min_order_value: 25,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: ["Splashify 2.0"],
    },
    {
      discount_name: "Down-sized even-keeled Graphic Interface",
      discount_code: "HIA048",
      discount_status: "draft",
      discount_applies_to: "all",
      discount_value: 30,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 80,
      discount_uses_count: 36,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 2,
      discount_min_order_value: 10,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Balanced upward-trending knowledgebase",
      discount_code: "YCI431",
      discount_status: "scheduled",
      discount_applies_to: "all",
      discount_value: 48,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 300,
      discount_uses_count: 238,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 10,
      discount_min_order_value: 60,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Synchronized zero administration concept",
      discount_code: "ZIC573",
      discount_status: "expired",
      discount_applies_to: "specific",
      discount_value: 37,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.recent(),
      discount_max_use: 150,
      discount_uses_count: 115,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 3,
      discount_min_order_value: 30,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: false,
      discount_product_ids: ["Mastering the Grid"],
    },
    {
      discount_name: "Fully-configurable reciprocal flexibility",
      discount_code: "IFB391",
      discount_status: "draft",
      discount_applies_to: "specific",
      discount_value: 44,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 20,
      discount_uses_count: 11,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 2,
      discount_min_order_value: 20,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: ["Mastering the Grid"],
    },
    {
      discount_name: "Profound content-based conglomeration",
      discount_code: "DHX819",
      discount_status: "active",
      discount_applies_to: "all",
      discount_value: 48,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 180,
      discount_uses_count: 161,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 5,
      discount_min_order_value: 50,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Horizontal zero administration open system",
      discount_code: "BBS686",
      discount_status: "active",
      discount_applies_to: "all",
      discount_value: 11,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 400,
      discount_uses_count: 281,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 15,
      discount_min_order_value: 100,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Pre-emptive bifurcated knowledgebase",
      discount_code: "SDL978",
      discount_status: "scheduled",
      discount_applies_to: "specific",
      discount_value: 26,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 60,
      discount_uses_count: 43,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 2,
      discount_min_order_value: 30,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: ["Mastering the Grid"],
    },
    {
      discount_name: "Reverse-engineered value-added hierarchy",
      discount_code: "KRD896",
      discount_status: "scheduled",
      discount_applies_to: "specific",
      discount_value: 50,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 500,
      discount_uses_count: 251,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 25,
      discount_min_order_value: 200,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: ["Mastering the Grid", "Yaya"],
    },
    {
      discount_name: "Ameliorated intermediate projection",
      discount_code: "XSB428",
      discount_status: "scheduled",
      discount_applies_to: "all",
      discount_value: 13,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 250,
      discount_uses_count: 222,
      discount_users_used: [faker.datatype.uuid(), faker.datatype.uuid()],
      discount_max_uses_per_user: 12,
      discount_min_order_value: 70,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
    {
      discount_name: "Adaptive directional customer loyalty",
      discount_code: "MVW194",
      discount_status: "active",
      discount_applies_to: "all",
      discount_value: 34,
      discount_type: "percentage",
      discount_start_date: faker.date.past(),
      discount_end_date: faker.date.future(),
      discount_max_use: 150,
      discount_uses_count: 152,
      discount_users_used: [faker.datatype.uuid()],
      discount_max_uses_per_user: 6,
      discount_min_order_value: 40,
      discount_shopId: faker.datatype.uuid(),
      discount_is_active: true,
      discount_product_ids: [],
    },
  ];
};

export default generateDiscounts;
